### ISSUE TITLE
Typo on main webpage

### ISSUE THREAD

**Issue by jhairssteven** [HaoruXue/haoruxue.github.io#1]
Hi, 
There is a typo on your main webpage on the `🦾 and quaduped 🦿` . Since you use WordPress I think it is easier for you to edit it.

https://github.com/HaoruXue/haoruxue.github.io/blob/8a7749fd1cc5d68ba7007185de4d0ae34f7997db/index.html#L188

**Comment by HaoruXue** [comment]
Never expected a ticket in this repo but thank you so much! 🤣

**Comment by HaoruXue** [comment]
fixed!
